# Generated by Django 6.0 on 2025-12-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
